#!/bin/bash

TOP=$(readlink -f $(dirname ${BASH_SOURCE:-$0})/..)

if [ ! -f $TOP/scripts/functions.sh ]; then
	echo "Failed to source functions.sh" && exit 1
else
	. $TOP/scripts/functions.sh
fi

setup_lbu() {
	mkdir -p $BUILDDIR/apkovl/etc/lbu/ || return $?
	cat > $BUILDDIR/apkovl/etc/fstab <<-FSTAB
		/dev/mmcblk0p1 /media/mmcblk0p1 vfat ro,relatime,fmask=0022,dmask=0022,errors=remount-ro 0 0
	FSTAB
	cat > $BUILDDIR/apkovl/etc/lbu/lbu.conf <<-LBU
		DEFAULT_CIPHER=aes-256-cbc
		LBU_MEDIA=mmcblk0p1
	LBU
}

add_sysfs_conf() {
	mkdir -p $BUILDDIR/apkovl/etc/init.d/ || return $?
	cat > $BUILDDIR/apkovl/etc/sysfs.conf <<-SYSFSCONF
		class/leds/network:act/trigger = netdev
		class/leds/network:act/rx = 1
		class/leds/network:act/tx = 1
		class/leds/network:act/device_name = $INTERFACE
		owner class/leds/network:act/device_name = admin:admin
		owner bus/nvmem/devices/3-00500/nvmem = admin:admin
	SYSFSCONF
}

setup_rc_local() {
	mkdir -p $BUILDDIR/apkovl/etc/local.d || return $?
	cat > "$BUILDDIR/apkovl/etc/local.d/01-create-user.start" <<-'RCUSER'
		#!/bin/ash

		read_password() {
		    echo -n $(dd if=/sys/bus/nvmem/devices/3-00500/nvmem skip=8192 bs=1 count=106 status=noxfer 2> /dev/null)
		}

		getent passwd admin >/dev/null 2>&1
		if [ $? -ne 0 ]; then
		    adduser -D admin
		    adduser admin audio
		    echo "admin:$(read_password)" | chpasswd -e
		fi
		passwd -l root
	RCUSER
	chmod 755 "$BUILDDIR/apkovl/etc/local.d/01-create-user.start"
	cat > "$BUILDDIR/apkovl/etc/local.d/02-configure-network.start" <<-RCNETWORK
		#!/bin/ash

		read_ipv4() {
		    local offset=$1
		    local ip=\$(dd if=/sys/bus/nvmem/devices/3-00500/nvmem skip=\$offset bs=1 count=4 status=noxfer 2> /dev/null | xxd -p)
		    printf "%d.%d.%d.%d" "0x\${ip:0:2}" "0x\${ip:2:2}" "0x\${ip:4:2}" "0x\${ip:6:2}"
		}

		ipaddr=\$(read_ipv4 8298)
		echo "auto $INTERFACE" >> /etc/network/interfaces
		if [ "\$ipaddr" = "0.0.0.0" ]; then
		    echo "iface $INTERFACE inet dhcp" >> /etc/network/interfaces
		else
		    dns=\$(read_ipv4 8310)
		    gateway=\$(read_ipv4 8306)
		    netmask=\$(read_ipv4 8302)
		    echo "nameserver \$dns" > /etc/resolv.conf
		    echo "iface $INTERFACE inet static" >> /etc/network/interfaces
		    echo "    address \$ipaddr" >> /etc/network/interfaces
		    echo "    netmask \$netmask" >> /etc/network/interfaces
		    echo "    gateway \$gateway" >> /etc/network/interfaces
		fi
	RCNETWORK
	chmod 755 "$BUILDDIR/apkovl/etc/local.d/02-configure-network.start"
	cat > "$BUILDDIR/apkovl/etc/local.d/03-add-mdev-entries.start" <<-'MDEV'
		#!/bin/ash

		echo "gpiomem		root:admin 0660" >> /etc/mdev.conf
		echo "ttyAMA0		root:admin 0660" >> /etc/mdev.conf

		/sbin/mdev -s
	MDEV
	chmod 755 "$BUILDDIR/apkovl/etc/local.d/03-add-mdev-entries.start"
}

setup_wpa() {
	if [[ -z "$SSID" ]]; then
		echo "Must set an SSID when using a wireless interface."
		return 1
	else
		mkdir -p $BUILDDIR/apkovl/etc/wpa_supplicant/ || return $?
		if [[ -z "$WPA_PSK" ]]; then
			cat > $BUILDDIR/apkovl/etc/wpa_supplicant/wpa_supplicant.conf <<-WPA
				network={
				    ssid="$SSID"
				    key_mgmt=NONE
				}
			WPA
		else
			wpa_passphrase "$SSID" $WPA_PSK > $BUILDDIR/apkovl/etc/wpa_supplicant/wpa_supplicant.conf
		fi
	fi
}

setup_network() {
	mkdir -p $BUILDDIR/apkovl/etc/network/ || return $?
	cat > $BUILDDIR/apkovl/etc/network/interfaces <<-INTF
		auto lo
		iface lo inet loopback

	INTF

	cat > $BUILDDIR/apkovl/etc/hostname <<-HOSTNAME
		pimodem
	HOSTNAME

	cat > $BUILDDIR/apkovl/etc/hosts <<-HOSTS
		127.0.0.1	pimodem
	HOSTS
}

setup_keymap() {
	local layout=$1
	local variant=$2
	mkdir -p $BUILDDIR/apkovl/etc/keymap || return $?
	mkdir -p $BUILDDIR/apkovl/etc/conf.d || return $?
	ln -sf /usr/share/bkeymaps/${layout}/${variant}.bmap.gz $BUILDDIR/apkovl/etc/keymap/${variant}.bmap.gz || return $?
	cat > $BUILDDIR/apkovl/etc/conf.d/loadkmap <<-LOADKMAP
		KEYMAP=/etc/keymap/${variant}.bmap.gz
	LOADKMAP
}

configure_run_levels() {
	mkdir -p $BUILDDIR/apkovl/etc/runlevels/sysinit || return $?
	mkdir -p $BUILDDIR/apkovl/etc/runlevels/boot || return $?
	mkdir -p $BUILDDIR/apkovl/etc/runlevels/default || return $?
	ln -sf /etc/init.d/urandom $BUILDDIR/apkovl/etc/runlevels/boot/urandom || return $?
	ln -sf /etc/init.d/networking $BUILDDIR/apkovl/etc/runlevels/boot/networking || return $?
	ln -sf /etc/init.d/loadkmap $BUILDDIR/apkovl/etc/runlevels/boot/loadkmap || return $?
	ln -sf /etc/init.d/swclock $BUILDDIR/apkovl/etc/runlevels/boot/swclock || return $?
	ln -sf /etc/init.d/sysfsconf $BUILDDIR/apkovl/etc/runlevels/boot/sysfsconf || return $?
	ln -sf /etc/init.d/modules $BUILDDIR/apkovl/etc/runlevels/sysinit/modules || return $?
	ln -sf /etc/init.d/modloop $BUILDDIR/apkovl/etc/runlevels/sysinit/modloop || return $?
	ln -sf /etc/init.d/hwdrivers $BUILDDIR/apkovl/etc/runlevels/sysinit/hwdrivers || return $?
	ln -sf /etc/init.d/local $BUILDDIR/apkovl/etc/runlevels/sysinit/local || return $?
	ln -sf /etc/init.d/chronyd $BUILDDIR/apkovl/etc/runlevels/default/chronyd || return $?
	ln -sf /etc/init.d/crond $BUILDDIR/apkovl/etc/runlevels/default/crond || return $?
	ln -sf /etc/init.d/dropbear $BUILDDIR/apkovl/etc/runlevels/default/dropbear || return $?
	ln -sf /etc/init.d/acpid $BUILDDIR/apkovl/etc/runlevels/default/acpid || return $?
	ln -sf /etc/init.d/pimodem $BUILDDIR/apkovl/etc/runlevels/default/pimodem || return $?

	if is_wireless_interface $INTERFACE; then
		ln -sf /etc/init.d/wpa_supplicant $BUILDDIR/apkovl/etc/runlevels/boot/wpa_supplicant || return $?
	fi
}

configure_world() {
	mkdir -p $BUILDDIR/apkovl/etc/apk || return $?
	echo "/media/mmcblk0p1/apks" >> $BUILDDIR/apkovl/etc/apk/repositories || return $?
	echo "/media/mmcblk0p1/pimodem" >> $BUILDDIR/apkovl/etc/apk/repositories || return $?
	echo "alpine-base" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "alsa-utils" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "alsa-lib" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "alsa-lib-dev" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "chrony" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "dropbear" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "dropbear-scp" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "kbd-bkeymaps" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "openssl" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo $PKGNAME >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo sudo >> $BUILDDIR/apkovl/etc/apk/world || return $?
	echo "tzdata" >> $BUILDDIR/apkovl/etc/apk/world || return $?

	if is_wireless_interface $INTERFACE; then
		echo "wireless-tools" >> $BUILDDIR/apkovl/etc/apk/world || return $?
		echo "wpa_supplicant" >> $BUILDDIR/apkovl/etc/apk/world || return $?
	fi
}

configure_timezone() {
	tz=$1
	ln -sf /usr/share/zoneinfo/${tz} $BUILDDIR/apkovl/etc/localtime || return $?
}

configure_sudoers() {
	echo "%admin ALL=(ALL) ALL" >> $BUILDDIR/apkovl/etc/sudoers
	chmod 440 $BUILDDIR/apkovl/etc/sudoers || return $?
}

configure_modules() {
	echo "ledtrig-netdev" >> $BUILDDIR/apkovl/etc/modules
}

generate_ssh_host_keys() {
	mkdir -p $BUILDDIR/apkovl/etc/dropbear || return $?
	keygen=$(which dropbearkey)
	if [ $? -eq 0 ]; then
		$keygen -t dss -s 1024 -f $BUILDDIR/apkovl/etc/dropbear/dropbear_dss_host_key >/dev/null 2>&1
		$keygen -t rsa -s 2048 -f $BUILDDIR/apkovl/etc/dropbear/dropbear_rsa_host_key >/dev/null 2>&1
		$keygen -t ecdsa -s 521 -f $BUILDDIR/apkovl/etc/dropbear/dropbear_ecdsa_host_key >/dev/null 2>&1
	fi
}

rm -rf $BUILDDIR/apkovl
mkdir -p $BUILDDIR/apkovl/ || exit 1
install -m 755 -D -t $BUILDDIR/apkovl/etc/apk/keys $BUILDDIR/keys/*.pub || exit 1

add_sysfs_conf || exit 1
setup_network || exit 1
configure_world || exit 1
configure_run_levels || exit 1
configure_timezone UTC || exit 1
setup_keymap us us || exit 1
setup_lbu || exit 1
setup_rc_local || exit 1
configure_sudoers || exit 1
configure_modules || exit 1
generate_ssh_host_keys || exit 1

if is_wireless_interface $INTERFACE; then
	setup_wpa || exit 1
fi

tar czf $BUILDDIR/pimodem.apkovl.tar.gz -C $BUILDDIR/apkovl . || exit 1

exit 0
